Update bootstrap.py to support --distribute to fix babel setup.py commands
With the old version which installed a recent dev version of setuptools
I was not able to go to /src/adhocracy and run the babel commands
defined in setup.cfg. The reason was probably a bug in setuptools:

  File "/home/csenger/.buildout/eggs/setuptools-0.6c12dev_r88846-py2.6.egg/setuptools/dist.py", line 403, in print_commands
  File "/home/csenger/.buildout/eggs/setuptools-0.6c12dev_r88846-py2.6.egg/pkg_resources.py", line 1954, in load
    """
ImportError: No module named upload_docs

Using distribute I can do

(adhocracy)/src/adhocracy$ adhocpy setup.py extract_messages